name: Created New Branch
 
on:
  create:

env:
  EVENT_NAME: ${{ github.event_name }}
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  actions:
    if: |
      github.event.ref_type == 'branch' &&
      github.ref_name != 'main' &&
      startsWith(github.ref_name, 'deploy-') == false &&
      startsWith(github.ref_name, 'feature-') == false &&
      startsWith(github.ref_name, 'patch-') == false &&
      startsWith(github.ref_name, 'fix-') == false &&
      startsWith(github.ref_name, 'revert-') == false &&
      startsWith(github.ref_name, 'test-') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Personalize new branch
      run: |
        find .env -type f -exec sed -i '' -e "/^DB_DATABASE=/s/=.*/=\'${{ env.BRANCH_NAME }}'/" {} \;
    - name: Configure application key
      run: |
        echo Installing dependencies based on lock file
        composer install --no-interaction --prefer-dist --optimize-autoloader
        php artisan key:generate
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -B ${{ env.BRANCH_NAME }}
        echo Commit .env updates
        git add -f .env
        git commit -m "Peronalize new branch"
        git push -f origin ${{ env.BRANCH_NAME }} || echo ""
        
